#!/usr/bin/env bash
## Homebrew Utilities
brew "bash"
brew "coreutils"
brew "findutils"

# Programming Languages

# AWS
brew "awscli"

# Runtimes
brew "nvm"
brew "goenv"
brew "pyenv"
brew "tfenv"

# Git
brew "git"
brew "git-flow"
brew "git-extras"

# Kubernetes
brew "kubectl"

# Utils
brew "bash-completion"
brew "curl", args: ["with-openssl"]
brew "geoip"
brew "jq"
brew "htop"
brew "openssl"
brew "packer"
brew "speedtest-cli"
brew "tree"
brew "watch"
brew "wget"

# QuickLook
brew "qlcolorcode"
brew "qlstephen"
brew "qlmarkdown"
brew "quicklook-json"
brew "webpquicklook"
brew "suspicious-package"
brew "quicklookase"
brew "qlvideo"
brew "qlImageSize"

# ZSH
brew "romkatv/powerlevel10k/powerlevel10k"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
