#!/usr/bin/env bash

cask_args appdir: '/Applications'

# Essential Mac applications
tap "caskroom/cask"
tap "caskroom/versions"

## Chat
cask "skype"
cask "slack"
cask "zoom"

## Cloud Storage
cask "dropbox"

## Database
cask "sequel-pro"

## Editors
cask "jetbrains-toolbox"
cask "vscode"

## Kubernetes
cask "aptakube"

## Internet Browsers
cask "google-chrome"

## MS Office
cask "microsoft-office"

## Media
cask "spotify"
cask "kindle"

## Programming Util
cask "codekit"
cask "docker"
cask "github"
cask "iterm2"
cask "postman"

## Utility
cask "alfred"
